"""empty message

Revision ID: 78d93f648a2d
Revises: 85ec260c7b05
Create Date: 2023-07-11 18:03:53.834613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d93f648a2d'
down_revision = '85ec260c7b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('transaction', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('exclusive', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('inclusive', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('inclusive')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('exclusive')
        batch_op.drop_column('remarks')
        batch_op.drop_column('transaction')
        batch_op.drop_column('date')
        batch_op.drop_column('period')

    # ### end Alembic commands ###
