"""empty message

Revision ID: 85ec260c7b05
Revises: 
Create Date: 2023-07-11 17:11:18.132617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ec260c7b05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('main_unit_no', sa.Integer(), nullable=True),
    sa.Column('property', sa.String(), nullable=True),
    sa.Column('general_contact', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('lease_start_date', sa.String(), nullable=True),
    sa.Column('lease_end_date', sa.String(), nullable=True),
    sa.Column('vacate_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('tenants')
    # ### end Alembic commands ###
